<?php

use App\Models\Tehsil;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TehsilSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $path_of_sql_file = database_path() . '/seeds/sql_files/tehsil_data.sql';
        DB::unprepared(file_get_contents($path_of_sql_file));
        $this->command->info('Tehsil table seeded from sql file!');


        // $aArrayRecord = array(
        //     array('id' => 1, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 16, 'tehsil_name' => 'Attock'),
        //     array('id' => 2, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 16, 'tehsil_name' => 'Fateh Jang'),
        //     array('id' => 3, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 16, 'tehsil_name' => 'Hassan Abdal'),
        //     array('id' => 4, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 16, 'tehsil_name' => 'Jand'),
        //     array('id' => 5, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 16, 'tehsil_name' => 'Pindi Gheb'),
        //     array('id' => 6, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 16, 'tehsil_name' => 'Hazro'),
        //     array('id' => 7, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 30, 'tehsil_name' => 'Ahmad Pur East'),
        //     array('id' => 8, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 30, 'tehsil_name' => 'Bahawalpur'),
        //     array('id' => 9, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 30, 'tehsil_name' => 'Hasilpur'),
        //     array('id' => 10, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 30, 'tehsil_name' => 'Khairpur Tamewali'),
        //     array('id' => 11, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 30, 'tehsil_name' => 'Yazman'),
        //     array('id' => 12, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 31, 'tehsil_name' => 'Bahawalnagar'),
        //     array('id' => 13, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 31, 'tehsil_name' => 'Chisthian'),
        //     array('id' => 14, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 31, 'tehsil_name' => 'Fortabbas'),
        //     array('id' => 15, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 31, 'tehsil_name' => 'Haroonabad'),
        //     array('id' => 16, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 31, 'tehsil_name' => 'Minchinabad'),
        //     array('id' => 17, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 14, 'tehsil_name' => 'Bhakkar'),
        //     array('id' => 18, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 14, 'tehsil_name' => 'Darya Khan'),
        //     array('id' => 19, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 14, 'tehsil_name' => 'Kalur Kot'),
        //     array('id' => 20, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 14, 'tehsil_name' => 'Mankera'),
        //     array('id' => 21, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 18, 'tehsil_name' => 'Chakwal'),
        //     array('id' => 22, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 18, 'tehsil_name' => 'Kallar Kahar'),
        //     array('id' => 23, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 18, 'tehsil_name' => 'Choa Saidan Shah'),
        //     array('id' => 24, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 18, 'tehsil_name' => 'Tala Gang'),
        //     array('id' => 25, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 33, 'tehsil_name' => 'De-Excluded DGK'),
        //     array('id' => 26, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 33, 'tehsil_name' => 'D.G.Khan'),
        //     array('id' => 27, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 33, 'tehsil_name' => 'Taunsa'),
        //     array('id' => 28, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 19, 'tehsil_name' => 'Chak Jhumra'),
        //     array('id' => 29, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 19, 'tehsil_name' => 'Faisalabad Sadar'),
        //     array('id' => 30, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 19, 'tehsil_name' => 'Faisalabad City'),
        //     array('id' => 31, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 19, 'tehsil_name' => 'Jaranwala'),
        //     array('id' => 32, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 19, 'tehsil_name' => 'Summundri'),
        //     array('id' => 33, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 19, 'tehsil_name' => 'Tandlian Wala'),
        //     array('id' => 34, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 5, 'tehsil_name' => 'Gujranwala'),
        //     array('id' => 35, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 5, 'tehsil_name' => 'Kamoke'),
        //     array('id' => 36, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 5, 'tehsil_name' => 'Nowshera Virkan'),
        //     array('id' => 37, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 5, 'tehsil_name' => 'Wazirabad'),
        //     array('id' => 38, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 6, 'tehsil_name' => 'Gujrat'),
        //     array('id' => 39, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 6, 'tehsil_name' => 'Kharian'),
        //     array('id' => 40, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 6, 'tehsil_name' => 'Sarai Alamgir'),
        //     array('id' => 41, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 8, 'tehsil_name' => 'Hafizabad'),
        //     array('id' => 42, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 8, 'tehsil_name' => 'Pindi Bhattian'),
        //     array('id' => 43, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 22, 'tehsil_name' => 'Chiniot'),
        //     array('id' => 44, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 22, 'tehsil_name' => 'Lalian'),
        //     array('id' => 45, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 22, 'tehsil_name' => 'Bhawana'),
        //     array('id' => 46, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 20, 'tehsil_name' => 'Jhang'),
        //     array('id' => 47, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 20, 'tehsil_name' => 'Shorkot'),
        //     array('id' => 48, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 20, 'tehsil_name' => 'Ahmad Pur Sial'),
        //     array('id' => 49, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 17, 'tehsil_name' => 'Jhelum'),
        //     array('id' => 50, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 17, 'tehsil_name' => 'Pind Dadan Khan'),
        //     array('id' => 51, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 17, 'tehsil_name' => 'Dina'),
        //     array('id' => 52, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 17, 'tehsil_name' => 'Sohawa'),
        //     array('id' => 53, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 3, 'tehsil_name' => 'Chunian'),
        //     array('id' => 54, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 3, 'tehsil_name' => 'Kasur'),
        //     array('id' => 55, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 3, 'tehsil_name' => 'Pattoki'),
        //     array('id' => 56, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 3, 'tehsil_name' => 'Kot Radha Kishan'),
        //     array('id' => 57, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 24, 'tehsil_name' => 'Jahanian'),
        //     array('id' => 58, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 24, 'tehsil_name' => 'Kabirwala'),
        //     array('id' => 59, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 24, 'tehsil_name' => 'Khanewal'),
        //     array('id' => 60, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 24, 'tehsil_name' => 'Mian Channu'),
        //     array('id' => 61, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 12, 'tehsil_name' => 'Khushab'),
        //     array('id' => 62, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 12, 'tehsil_name' => 'Noor Pur'),
        //     array('id' => 63, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 12, 'tehsil_name' => 'Quaidabad'),
        //     array('id' => 64, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 1, 'tehsil_name' => 'Lahore Cantt.'),
        //     array('id' => 65, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 1, 'tehsil_name' => 'Lahore City'),
        //     array('id' => 66, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 36, 'tehsil_name' => 'Choubara'),
        //     array('id' => 67, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 36, 'tehsil_name' => 'Karor Lal Esan'),
        //     array('id' => 68, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 36, 'tehsil_name' => 'Layyah'),
        //     array('id' => 69, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 25, 'tehsil_name' => 'Dunya Pur'),
        //     array('id' => 70, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 25, 'tehsil_name' => 'Kahror Pacca'),
        //     array('id' => 71, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 25, 'tehsil_name' => 'Lodhran'),
        //     array('id' => 72, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 35, 'tehsil_name' => 'Alipur'),
        //     array('id' => 73, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 35, 'tehsil_name' => 'Jatoi'),
        //     array('id' => 74, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 35, 'tehsil_name' => 'Kot Addu'),
        //     array('id' => 75, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 35, 'tehsil_name' => 'Muzaffargarh'),
        //     array('id' => 76, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 10, 'tehsil_name' => 'Malakwal'),
        //     array('id' => 77, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 10, 'tehsil_name' => 'M.B.Din'),
        //     array('id' => 78, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 10, 'tehsil_name' => 'Phalia'),
        //     array('id' => 79, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 13, 'tehsil_name' => 'Isakhel'),
        //     array('id' => 80, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 13, 'tehsil_name' => 'Mianwali'),
        //     array('id' => 81, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 13, 'tehsil_name' => 'Piplan'),
        //     array('id' => 82, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 23, 'tehsil_name' => 'Jalal Pur Pirwala'),
        //     array('id' => 83, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 23, 'tehsil_name' => 'Multan City'),
        //     array('id' => 84, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 23, 'tehsil_name' => 'Multan Saddar'),
        //     array('id' => 85, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 23, 'tehsil_name' => 'Shujabad'),
        //     array('id' => 86, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 9, 'tehsil_name' => 'Narowal'),
        //     array('id' => 87, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 9, 'tehsil_name' => 'Shakargarh'),
        //     array('id' => 88, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 7, 'district_id' => 29, 'tehsil_name' => 'Depalpur'),
        //     array('id' => 89, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 7, 'district_id' => 29, 'tehsil_name' => 'Okara'),
        //     array('id' => 90, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 7, 'district_id' => 29, 'tehsil_name' => 'Renala Khurd'),
        //     array('id' => 91, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 7, 'district_id' => 28, 'tehsil_name' => 'Arif Wala'),
        //     array('id' => 92, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 7, 'district_id' => 28, 'tehsil_name' => 'Pakpattan'),
        //     array('id' => 93, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 7, 'district_id' => 28, 'tehsil_name' => 'Arazi Khan'),
        //     array('id' => 94, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 32, 'tehsil_name' => 'Khanpur'),
        //     array('id' => 95, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 32, 'tehsil_name' => 'Liquat Pur'),
        //     array('id' => 96, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 32, 'tehsil_name' => 'R.Y.Khan'),
        //     array('id' => 97, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 8, 'district_id' => 32, 'tehsil_name' => 'Sadiqabad'),
        //     array('id' => 98, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 34, 'tehsil_name' => 'De-Excluded RJP'),
        //     array('id' => 99, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 34, 'tehsil_name' => 'Jampur'),
        //     array('id' => 100, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 34, 'tehsil_name' => 'Rajanpur'),
        //     array('id' => 101, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 34, 'tehsil_name' => 'Rojhan'),
        //     array('id' => 102, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 15, 'tehsil_name' => 'Gujjar Khan'),
        //     array('id' => 103, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 15, 'tehsil_name' => 'Kahuta'),
        //     array('id' => 104, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 15, 'tehsil_name' => 'Kaller Syedan'),
        //     array('id' => 105, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 15, 'tehsil_name' => 'Kotli Sattian'),
        //     array('id' => 106, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 15, 'tehsil_name' => 'Murree'),
        //     array('id' => 107, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 15, 'tehsil_name' => 'Rawalpindi'),
        //     array('id' => 108, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 15, 'tehsil_name' => 'Taxila'),
        //     array('id' => 109, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 7, 'district_id' => 27, 'tehsil_name' => 'Chichawatni'),
        //     array('id' => 110, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 7, 'district_id' => 27, 'tehsil_name' => 'Sahiwal'),
        //     array('id' => 111, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 11, 'tehsil_name' => 'Bhalwal'),
        //     array('id' => 112, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 11, 'tehsil_name' => 'Sargodha'),
        //     array('id' => 113, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 11, 'tehsil_name' => 'Shahpur'),
        //     array('id' => 114, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 11, 'tehsil_name' => 'Sillanwali'),
        //     array('id' => 115, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 11, 'tehsil_name' => 'Kot Momin'),
        //     array('id' => 116, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 11, 'tehsil_name' => 'Sahiwal'),
        //     array('id' => 117, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 2, 'tehsil_name' => 'Ferozewala'),
        //     array('id' => 118, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 2, 'tehsil_name' => 'Muridke'),
        //     array('id' => 119, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 2, 'tehsil_name' => 'Sharqpur'),
        //     array('id' => 120, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 4, 'tehsil_name' => 'Nankana Sahib'),
        //     array('id' => 121, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 4, 'tehsil_name' => 'Sangla Hill'),
        //     array('id' => 122, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 4, 'tehsil_name' => 'Shah Kot'),
        //     array('id' => 123, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 2, 'tehsil_name' => 'Safdarabad'),
        //     array('id' => 124, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 2, 'tehsil_name' => 'Sheikhupura'),
        //     array('id' => 125, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 7, 'tehsil_name' => 'Daska'),
        //     array('id' => 126, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 7, 'tehsil_name' => 'Pasrur'),
        //     array('id' => 127, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 7, 'tehsil_name' => 'Sialkot'),
        //     array('id' => 128, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 2, 'district_id' => 7, 'tehsil_name' => 'Sambrial'),
        //     array('id' => 129, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 21, 'tehsil_name' => 'Gojra'),
        //     array('id' => 130, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 21, 'tehsil_name' => 'Kamalia'),
        //     array('id' => 131, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 21, 'tehsil_name' => 'T.T.Singh'),
        //     array('id' => 132, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 26, 'tehsil_name' => 'Burewala'),
        //     array('id' => 133, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 26, 'tehsil_name' => 'Mailsi'),
        //     array('id' => 134, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 6, 'district_id' => 26, 'tehsil_name' => 'Vehari'),
        //     array('id' => 135, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 33, 'tehsil_name' => 'D.G. Khan II'),
        //     array('id' => 136, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 38, 'tehsil_name' => 'Koh e Suleman'),
        //     array('id' => 137, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 38, 'tehsil_name' => 'Taunsa I'),
        //     array('id' => 138, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 38, 'tehsil_name' => 'Taunsa II'),
        //     array('id' => 139, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 9, 'district_id' => 33, 'tehsil_name' => 'Kot Chutta'),
        //     array('id' => 140, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 4, 'district_id' => 18, 'tehsil_name' => 'Lava'),
        //     array('id' => 141, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 3, 'tehsil_name' => 'Kasur2'),
        //     array('id' => 142, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 1, 'district_id' => 3, 'tehsil_name' => 'Phool Nagar'),
        //     array('id' => 143, 'province_id' => 1, 'zone_id' => 2, 'division_id' => 5, 'district_id' => 20, 'tehsil_name' => '18 Hazari'),
        //     array('id' => 144, 'province_id' => 1, 'zone_id' => 1, 'division_id' => 3, 'district_id' => 12, 'tehsil_name' => 'Naushera'),
        // );

        // foreach ($aArrayRecord as $aRecord) {
        //     Tehsil::firstOrCreate($aRecord);
        // }
    }
}
